openapi: 3.0.0
info:
  title: T-shirt store API
  descreption: API for e-com store
  version: 1.0.0
  contact:
    email: aarishkhan@gmail.com
    url: https://aarishkhsn.dev

servers:
  - url: "{protocol}://localhost:3000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
components:
  securitySchemes:
    cookieAuth: # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer
